replicaCount: 1

image:
  repository: ghcr.io/alexohneander/sim-free
  pullPolicy: Always
  tag: sha-81275a55040b066cbb46f5bdb07eabd604463e91

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000
  annotations: {}


gateway:
  enabled: true
  annotations: {}
  parentRefs:
    - name: gateway
      namespace: nginx-gateway
      sectionName: sim-free-https
  hostnames:
    - sim-free.dev-null.rocks
  path: /

redis:
  persistence:
    storageClassName: proxmox-data-xfs

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}
