replicaCount: 1

image:
  repository: ghcr.io/alexohneander/sim-free
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: sim-free.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

gateway:
  enabled: false
  annotations: {}
  parentRefs:
    - name: public-gateway
      sectionName: https
  hostnames:
    - sim-free.example.com
  path: /

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}
