ingress:
  enabled: true
  className: nginx
  hosts:
    - host: sim-free.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - sim-free.example.com
      secretName: sim-free-tls
